# Generated by Django 4.2.19 on 2025-03-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('clues', models.JSONField()),
                ('fun_fact', models.JSONField()),
                ('trivia', models.JSONField()),
            ],
        ),
    ]
